exec-once = mako
exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar
# exec-once = iwgtk --tray

# Clipboard manager
exec-once = wl-clip-persist --clipboard regular
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Session
# exec-once = systemctl --user start graphical-session.target

# Pokit
# exec-once = usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent

# user environment
exec-once = systemctl --user import-environment

# Applets
exec-once = blueman-applet

# Emacs
exec-once = emacs --daemon
