background {
  color = rgba(0,50,70,1.0)
}

input-field {
  size = 200, 50
  outline_thickness = 2
  dots_size = 0.33
  dots_spacing = 0.15
  dots_center = true
  outer_color = rgba(90,90,90,1.0)
  inner_color = rgba(30,30,30,1.0)
  font_color = rgba(220,220,220,1.0)
}
