# https://wiki.hyprland.org/Configuring/Variables/#input

input {
  kb_layout = se, us, gr
  kb_variant = , , polytonic
  kb_model =
  kb_options = grp:lctrl_lwin_toggle,ctrl:nocaps
  kb_rules =

  repeat_rate = 30
  repeat_delay = 250

  follow_mouse = 1
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

  touchpad {
      natural_scroll = false
      disable_while_typing = true
      middle_button_emulation = false
  }
}

# misc {
#     middle_click_paste = false
# }

# Optional: Fully disable middle click to prevent accidents
# bind = , mouse:274, device:"syna801a:00-06cb:cec6-touchpad", exec, ;
# bind = , mouse:274, exec, ;

cursor {
  no_hardware_cursors = true
}

# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
