# https://wiki.hyprland.org/Configuring/Variables/#input

input {
  kb_layout = se, us
  kb_variant =
  kb_model =
  kb_options =
  kb_rules =

  repeat_rate = 30
  repeat_delay = 250

  follow_mouse = 1
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

  touchpad {
      natural_scroll = false
      disable_while_typing = true
      middle_button_emulation = false
  }
}

cursor {
  no_hardware_cursors = true
}

# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
