# See https://wiki.hyprland.org/Configuring/Monitors/

# monitor = name, resolution, position, scale

monitor = , preferred, auto, auto
# monitor = eDP-1, preferred, auto, 1
# monitor = HDMI-A-1, 2560x1440@60, 0x0, 1
