# See https://wiki.hyprland.org/Configuring/Monitors/

# monitor = name, resolution, position, scale

# monitor = , preferred, auto, auto
# monitor = , preferred, auto, auto, mirror, eDP-1
monitor = eDP-1, preferred, auto, auto
monitor = DP-1, preferred, auto, auto, mirror, eDP-1
# monitor = eDP-1, preferred, auto, auto, mirror

# workspace = 1, monitor:eDP-1
# workspace = 1, monitor:DP-1
