# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Float mpv and cgoban
windowrule = float on, match:class mpv
# windowrule = float on, match:class org.cgoban.CGoban3

# Scratch terminals

# Scratch terminals have no borders and gaps
windowrule = border_size 0, match:title scratch-.*
windowrule = no_anim on, match:title scratch-.*

# Upper scratch terminal
windowrule = workspace special:up, match:title scratch-up
windowrule = float on, match:title scratch-up
windowrule = size monitor_w*0.6 monitor_h*0.3, match:title scratch-up
windowrule = move monitor_w*0.2 30, match:title scratch-up

# Lower scratch terminal
windowrule = workspace special:down, match:title scratch-down
windowrule = float on, match:title scratch-down
windowrule = size monitor_w*0.6 monitor_h*0.3, match:title scratch-down
windowrule = move monitor_w*0.2 monitor_h*0.7, match:title scratch-down
