# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Float mpv and cgoban
windowrule = float on, match:class mpv
# windowrule = float on, match:class org.cgoban.CGoban3

# Scratch terminals

# Scratch terminals have no borders and gaps
windowrule = border_size 0, match:title scratch-.*
windowrule = no_anim on, match:title scratch-.*

# Scratch terminals float and are visible on all workspaces
windowrule = float on, match:title scratch-.*
# windowrule = pin on, match:title scratch-.*   # <-- visible on all workspaces

# Upper scratch terminal
windowrule = size monitor_w*0.6 monitor_h*0.28, match:title scratch-up
windowrule = move monitor_w*0.2 30, match:title scratch-up

# Lower scratch terminal
windowrule = size monitor_w*0.6 monitor_h*0.28, match:title scratch-down
windowrule = move monitor_w*0.2 monitor_h*0.72, match:title scratch-down
